name: Java ci build docker
run-name: docker build @${{ github.actor }}
on:
  workflow_run:
    workflows: ["Java CI test and build with Gradle"]
    types:
      - completed 
jobs: 
    build:
        runs-on: ubuntu-latest
        env:
            ACTION_STEP_DEBUG: true
        steps:
          - name: Checkout
            uses: actions/checkout@v4

          - name: setup java
            uses: actions/setup-java@v4
            with:
                distribution: 'temurin'
                java-version: 17
          - name: remove docker config
            run: |
                docker logout
                rm -rf ~/.docker/config.json 
          - name: login docker
            uses: docker/login-action@v3
            with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_TOKEN }}
                
          - name: set up QEMU
            uses: docker/setup-qemu-action@v3
            
          - name: set up Docker build
            uses: docker/setup-buildx-action@v3
            
          - name: build and push
            uses: docker/build-push-action@v6
            with:
                push: true
                tags: user/app:latest