name: Java dependency sumission
run-name: Deploy by @${{ github.actor }}
on:
  workflow_run:
    workflows: ["Java CI with Gradle"]
    types:
      - completed
jobs:
  build:
    name: dependencies
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
      - name: checkout
        uses: actions/checkout@v4

       - name: setup java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17
        - name: create dependency graph
        uses: gradle/actions/dependency-submission@v4