name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
jobs: 
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: 'Set up JDK 17'
              uses: actions/setup-java@v4
              with:
                java-version: '17'
                distribution: 'temurin'
            - name: 'Setup Gradle'
              uses: gradle/gradle-build-action@v2
              #uses: gradle/actions/setup-gradle@v4
            - name: 'Gradle berechtigungen'
              run: chmod +x ./gradlew
            - name: 'Build with Gradle'
              run: ./gradlew build
              
dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0